### ISSUE TITLE
SetWindowDisplayAffinity

### ISSUE THREAD

**Issue by wilkster** [tylerjcw/YACS#1]
On windows 10 and above you can exclude the previewGui from being captured (and thus not require the previewXOffset/previewYOffset by calling the following just after the GUI is created:

 if NOT DllCall("User32\SetWindowDisplayAffinity", "Ptr", previewGui.hWnd, "Int", 0x00000011, "Int") ; WDA_EXCLUDEFROMCAPTURE
      MsgBox("Failed to set affinity")

Change:
I am seeing an error with this on Windows 10 (not working getting an error code 8), but it works on my Windows 11 machines. I think it has to do with layered windows. Still investigating. 

Change:
Creating the GUI without layering, setting affinity then setting layering seems to work on my Windows 10 machine.
   previewGui := Gui("+AlwaysOnTop -Caption +ToolWindow -DPIScale")
   ;----------------------------------------------------------------------
   ; Make sure this GUI is not part of the screen capture (Windows 10+)
   ;----------------------------------------------------------------------
   if NOT DllCall("User32\SetWindowDisplayAffinity", "Ptr", previewGui.hWnd, "Int", 0x00000011, "Int") ; WDA_EXCLUDEFROMCAPTURE
      OutputDebug("Failed to set affinity:" A_LastError)
   previewGui.Opt(" +E0x80000")

Could probably detect failure/success then adjust the previewXOffset/previewYOffset accordingly.

**Comment by tylerjcw** [comment]
Ahh, thank you for that! I was looking for how to do that, much appreciated!
As for the offset, I'm stil going to keep it in there, I'll just adjust it so it doesn't change on captureArea increase and decrease now.
